### ISSUE TITLE
Not able to build due to versions incompatibility/collision

### ISSUE THREAD

**Issue by ppanero** [inveniosoftware/invenio-accounts#265]
Cryptography has pinned [idna >= 2.1](https://github.com/pyca/cryptography/blob/master/setup.py#L287)
Requests has pinned [idna>=2.5,<2.7](https://github.com/requests/requests/blob/master/setup.py#L53)

Lastest idna release is [2.7](https://github.com/kjd/idna/tree/v2.7) Therefore it fails to build. In my own project I have fixed it pinning the dependency but maybe it is nice to pin it here too.

**Comment by lnielsen** [comment]
This is identical to #243 which happened when idna v2.6 was released. Requests library is set to be updated within a week (see https://github.com/requests/requests/issues/4681) which will solve the issue, but we'll have the same problem again when idna v2.8 is released so likely we need to do something about it so it won't break in the future.

That said, probably the place idna should be pinned is not in invenio-accounts, since there's no dependency on requests.

**Comment by ppanero** [comment]
Hmm its true there is not dependency on requests but there is on Cryptography (which has a dependency on idna). Im closing this, since is easily solvable by pinning in my own app. If you consider necessary open again, happy to help. 

And Thanks for the info!

**Comment by lnielsen** [comment]
I think it's still an issue, but I'm not sure where the dependency comes from - this is definitely going to happen again in the future, so I'm quite sure we need to pin idna, just need to be in the right package
