### ISSUE TITLE
Login error messages too explicit

### ISSUE THREAD

**Issue by FlorianCassayre** [inveniosoftware/invenio-accounts#344]
`Flask-Admin` provides error messages that are too explicit and can help an attacker (e.g. known email but invalid password). In my opinion this should be disabled by default in `invenio-accounts`. Example in ILS:

![localhost_3000_login_next=%2F](https://user-images.githubusercontent.com/9027075/91810411-1f89d980-ec2e-11ea-85e3-f8ebdb5b54fb.png)
![localhost_3000_login_next=%2F (1)](https://user-images.githubusercontent.com/9027075/91810414-21539d00-ec2e-11ea-95ac-d339918b596a.png)

**Comment by lnielsen** [comment]
We have had discussions about this among architects some time ago, and it's not clear that this is a security issue. As an example, from Google and Amazon logins you can learn that a given email address is already registered (exposing the same information as above).

The problem comes not from the login form, but from the signup page. If you cannot inform a user that a given email address is already registered, then the only way to not leak the email address is to tell the user "We have sent you an email". Then the user has to wait and see if the email arrives. This type of registration doesn't leak the email, but it will significantly reduce the signup rate (hence probably why Google/Amazon is not doing it).

**Comment by FlorianCassayre** [comment]
Thanks for the followup. In the meantime I had come up with the same solution you described for the registration workflow, and as you pointed it can be confusing for the users trying to signup with an existing email. Now I've checked some resources online, the attack that takes advantage of this pattern is known as "_username enumeration_" and its seriousness is indeed controversial.

Since you already discussed about it, it would therefore make sense to label this as `wontfix`.
