### ISSUE TITLE
Security loophole

### ISSUE THREAD

**Issue by nkenobi** [inveniosoftware/invenio-accounts#366]
Package version (if known): <version>latest

## Describe the bug
There is a loophole whereby users requiring confirmation can register. Then without confirmation, they can reset password and are logged into the system.

## Steps to Reproduce
Register (with requires confirmation)
Dont confirm the email
Reset password
Then they are logged in.

## Context
The ResetPasswordView calls flask login_user which doesn't check the confirmation unlike RegisterView

**Comment by lnielsen** [comment]
I'm not able to reproduce this bug.

1. First of all, I set ``SECURITY_LOGIN_WITHOUT_CONFIRMATION = False`` otherwise you're anyway logged in directly after the registration action.

2. I register an account.

3. I try to recover the password 

Result, I get an error "Email requires confirmation".

That said, even if I used the reset password option, the email is sent to the address an essentially works as a confirmation of the email address.
