### ISSUE TITLE
Upgrade from Flask-Security to Flask-Security-Too

### ISSUE THREAD

**Issue by GraemeWatt** [inveniosoftware/invenio-accounts#375]
Invenio-Accounts installs `Flask-Security>=3.0.0` where the latest v3.0.0 from [PyPI](https://pypi.org/project/Flask-Security/) was released on 14th June 2017.  The [README.rst](https://github.com/mattupstate/flask-security/blob/develop/README.rst) in the corresponding [GitHub repository](https://github.com/mattupstate/flask-security) says:

> This project is non maintained anymore. Consider the [Flask-Security-Too](https://flask-security-too.readthedocs.io/en/stable/) project as an alternative.

Would you consider upgrading to [Flask-Security-Too](https://pypi.org/project/Flask-Security-Too/)?  It provides a new [`MailUtil`](https://flask-security-too.readthedocs.io/en/stable/api.html#flask_security.MailUtil) class that we wanted to use to customise HEPData security emails (HEPData/hepdata#383).

**Comment by lnielsen** [comment]
Sorry @GraemeWatt, just seeing this now. Yes, we're aware of the issue with Flask-Security, and we do have to upgrade to Flask-Security-Too - just hard to get the time. Clearly, it's an issue to be dependent on a core library without maintenance.

**Comment by lnielsen** [comment]
I made a half-day try to see how hard it would be to upgrade to latest Flask-Security-Too. At this point, the biggest change I've detected is the requirement for adding ``fs_uniqifier`` to the model. Basically a UUID is not generated for each user now, so e.g. the identity instead of having a ``UserNeed(1)`` now has a ``UserNeed(<uuid>)``. This impacts nearly all modules that does some sort of permission checking for records and user ids. It doesn't seem like a simple fix either. 

On top of that I've reviewed what was added and fixed in Flask-Security-Too. The library has grown quite a lot, and a lot of features has been added, most of them for multifactor auth or things we don't need or use. I'm slightly concerned seeing the release notes. There seem to be a fast release cycle which often breaks stuff or introduce vulnerabilities.

Given that we've already had to disable stuff in the Flask-Security I'm not overly happy with adding a large codebase with lots of features we don't need. Overall, the best is that Invenio is connected to an existing identity provider that handles the sign-in/multifactor etc so I don't see big use of multifactor directly in Invenio.

Thus, I'm not sure if it's a good idea to migrate to Flask-Security-Too. We have a stable solution right now, and I think it's likely less effort to maintain our own fork of the existing code base, than upgrading to Flask-Security-Too and trying to keep up with it and potentially introduce a much large attack surface.

Just my thoughts after doing some evaluation of it today.

**Comment by lnielsen** [comment]
So, we've discussed this among the architects. The decision is to fork Flask-Security (v3) and maintain it ourselves. We think this will be 1) less effort near-term and long-term and 2) more stable and less security issues. 

Invenio should normally be connected with an identity provider (e.g either institutional login system or global login system like ORCID). This will ensure that we keep up with latest authentication developments and can focus our efforts on repository features. E.g. multifactor authentication I'd much rather have the identity provider do, than trying to implement it in Invenio via Flask-Security-Too.
